storage.local.enabled=true
storage.local.path=com-id-storage.properties

storage.remote.enabled=false
storage.remote.driverClassName=
storage.remote.jdbcUrl=jdbc:mariadb://127.0.0.1:3306/mindustry
storage.remote.username=root
storage.remote.password=change-me
storage.remote.tableName=jump_com_ids

api.enabled=true
api.host=127.0.0.1
api.port=19115
api.requireToken=false
api.token=change-me
