# 本地存储
本地存储.启用=true
本地存储.文件=com-id-storage.properties

# 远程数据库
远程数据库.启用=false
远程数据库.驱动类名=
远程数据库.JDBC地址=jdbc:mariadb://127.0.0.1:3306/mindustry
远程数据库.用户名=root
远程数据库.密码=change-me
远程数据库.表名=jump_com_ids

# 接口服务
接口服务.启用=true
接口服务.主机=127.0.0.1
接口服务.端口=19115
接口服务.验证令牌=false
接口服务.令牌=change-me
